### ISSUE TITLE
[v5.10.x] Review README Documentation For IAM Helm Resources

### ISSUE THREAD

**Issue by chirangaalwis** [wso2/kubernetes-is#229]
**Description:**
It is required to review the README documentation for WSO2 IAM product Helm resources aligning them with latest changes.

**Sub Tasks:**
- [x] Document how to enable persistence/sharing of runtime artifacts (see https://github.com/wso2/kubernetes-is/issues/242#issuecomment-666512083)
- [x] Document how to override the Kubernetes Storage Class of the MySQL deployment (see https://github.com/wso2/kubernetes-is/issues/243#issuecomment-666502757)
- [x] Document about customizing key stores and trust stores (link to https://github.com/wso2/container-guide/issues/14)
- [x] Code/Peer review

**Related Issues:**
https://github.com/wso2/kubernetes-is/issues/224, https://github.com/wso2/kubernetes-apim/issues/392

**Comment by chirangaalwis** [comment]
Fixed in https://github.com/wso2/kubernetes-is/pull/258.
